/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e7e8e9",
        "on-primary-container": "#fefcff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#111c2d",
        "primary": "#0058be",
        "on-surface": "#191c1d",
        "surface-dim": "#d9dadb",
        "primary-container": "#2170e4",
        "inverse-on-surface": "#f0f1f2",
        "on-surface-variant": "#424754",
        "on-tertiary-container": "#fffbff",
        "primary-fixed": "#d8e2ff",
        "surface-tint": "#005ac2",
        "inverse-surface": "#2e3132",
        "on-error": "#ffffff",
        "tertiary": "#825100",
        "background": "#f8f9fa",
        "tertiary-fixed-dim": "#ffb95f",
        "error": "#ba1a1a",
        "surface-container": "#edeeef",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "tertiary-container": "#a36700",
        "tertiary-fixed": "#ffddb8",
        "outline-variant": "#c2c6d6",
        "surface-container-low": "#f3f4f5",
        "secondary-fixed": "#d8e3fb",
        "on-tertiary-fixed": "#2a1700",
        "surface-variant": "#e1e3e4",
        "on-secondary-fixed-variant": "#3c475a",
        "outline": "#727785",
        "surface-bright": "#f8f9fa",
        "primary-fixed-dim": "#adc6ff",
        "surface-container-highest": "#e1e3e4",
        "secondary-fixed-dim": "#bcc7de",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001a42",
        "on-primary-fixed-variant": "#004395",
        "surface": "#f8f9fa",
        "surface-container-lowest": "#ffffff",
        "secondary": "#545f73",
        "on-tertiary-fixed-variant": "#653e00",
        "on-background": "#191c1d",
        "inverse-primary": "#adc6ff",
        "on-secondary-container": "#586377",
        "secondary-container": "#d5e0f8",
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
        info: '#0ea5e9',
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "16px",
        "margin": "24px",
        "xs": "4px",
        "sm": "8px",
        "base": "4px",
        "md": "16px",
        "xl": "32px",
        "lg": "24px"
      },
      boxShadow: {
        'premium': '0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03)',
        'bento': '0 0 0 1px rgba(0,0,0,0.05), 0 2px 4px rgba(0,0,0,0.05), 0 12px 24px rgba(0,0,0,0.05)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
